# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ios-e2e"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Cancel current builds if there's a newer commit on the same branch
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up github keys
        run: git config core.sshCommand "ssh -i ~/.ssh/id_ed25519 -F /dev/null"

      - name: Install deps via Yarn
        run: yarn setup

      - name: Check for frozen lockfile
        run: yarn check-lockfile

      - name: Audit CI
        run:  yarn audit-ci --moderate --config audit-ci.json

      - name: Lint
        run: yarn lint

      - name: Build the extension with LavaMoat
        run: yarn build
