name: CI

on: [pull_request, workflow_dispatch]

jobs:
  install-dep:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - uses: actions/checkout@v3

      - name: Set up github keys
        run: git config core.sshCommand "ssh -i ~/.ssh/id_ed25519 -F /dev/null"

      - name: Install deps via Yarn
        run: yarn setup

      - name: Check for frozen lockfile
        run: yarn check-lockfile
  audit:
    runs-on: ubuntu-latest
    needs: [install-deps]
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Audit CI
        run:  yarn audit-ci --moderate --config audit-ci.json

  lint:
    runs-on: ubuntu-latest
    needs: [install-deps]
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: [install-deps]
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Build the extension with LavaMoat
        run: yarn build
